### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by pkjindal111** [jaikumarpd/onedrive#1]
Cant get access to onedrive, get the following error- Undefined property: stdClass::$refresh_token

**Comment by pkjindal111** [comment]
using this '$onedrive->get_code_url();' i generated the link, this link gave me the code, access token and refresh token, i manually added the access token and refresh token in onedrive_absctract.php in function defined- 'token_functionality';

now its working! but adding static data like this is ok?? can you suggest a solution to it?

**Comment by robertantonyjaikumar** [comment]
It is working right ?
