### ISSUE TITLE
Not able to download files

### ISSUE THREAD

**Issue by pkjindal111** [jaikumarpd/onedrive#2]
When try to download file i just get this- 'string(0) ""'

**Comment by robertantonyjaikumar** [comment]
Can you please show some snippets?

**Comment by pkjindal111** [comment]
> Can you please show some snippets?

thx for replying, this is what i'm doing : 
$onedrive = new onedrive_personal();
$onedrive->download_file($file_id);

for access token and refresh token i have made some changes in core files and authentication is just working fine. all other functions - creating file, uploading file, etc.. are working perfect.

but when try to download file it do not start download and just returns- string(0) ""

note: i have also ensured that i'm using the right file id

**Comment by pkjindal111** [comment]
Any response bro??

**Comment by robertantonyjaikumar** [comment]
Sorry for the Late reply.

I will check and update the build
