### ISSUE TITLE
cURL Error

### ISSUE THREAD

**Issue by pkjindal111** [jaikumarpd/onedrive#3]
For remote file transfer it gives this error - cURL Error #:TCP connection reset by peer

File size is 64MB, After 60-80 seconds of starting upload i get this error,

what i already tried:
- tuned off the firewall
- updated the curl
- using latest version of php 7.3
- tried https and http, both version

please reply asap, its urgent!!

**Comment by robertantonyjaikumar** [comment]
are you using onedrive personal or business ?

**Comment by pkjindal111** [comment]
business

**Comment by robertantonyjaikumar** [comment]
Increase the timeout onedrive_abstarct.php line 204
 CURLOPT_TIMEOUT => 30000,
It will work

**Comment by pkjindal111** [comment]
isn't the time 30000 is in seconds? it should be enough
